name: main Build Push Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coding-theory-calculator:${{ github.sha }}

      
  deploy:
    needs: [build_and_push]
    environment: 
      name: Production
      url: https://coding-theory-calculator.billylee.me
    runs-on: ubuntu-latest
    steps:
    - name: Installing SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
      
    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no billy@${{ secrets.DROPLET_IP }} << 'EOF'
          cd ~/coding-theory-calculator
          echo IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/coding-theory-calculator:${{ github.sha }} > .env
          docker compose pull
          docker compose up -d
        EOF
